language: go
go_import_path: google-maps-services-go

# See https://github.com/travis-ci/gimme/blob/master/.testdata/binary-linux for known golang versions
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip
